### ISSUE TITLE
Missing parameters for inspection jobs, raised by workload operator

### ISSUE THREAD

**Issue by fridex** [thoth-station/amun-api#173]
When scheduling inspections, I got following errors:

```
2019-06-03 09:16:39,936 [1] ERROR    thoth.common.openshift:1393: Failed to process template: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Template.template.openshift.io \"amun-inspection-job-with-cpu\" is invalid: [template.parameters[0]: Required value: template.parameters[0]: parameter THOTH_REGISTRY is required and must be specified, template.parameters[1]: Required value: template.parameters[1]: parameter THOTH_INFRA_NAMESPACE is required and must be specified]","reason":"Invalid","details":{"name":"amun-inspection-job-with-cpu","group":"template.openshift.io","kind":"Template","causes":[{"reason":"FieldValueRequired","message":"Required value: template.parameters[0]: parameter THOTH_REGISTRY is required and must be specified","field":"template.parameters[0]"},{"reason":"FieldValueRequired","message":"Required value: template.parameters[1]: parameter THOTH_INFRA_NAMESPACE is required and must be specified","field":"template.parameters[1]"}]},"code":422}
--
  | 2019-06-03 09:16:40,313 [1] ERROR    thoth.workload_operator:190: Failed run requested workload for event ResourceInstance[ConfigMap]:
  | apiVersion: v1
  | data:
  | run_method_name: run_inspection_job
  | run_method_parameters: '{"memory_requests": "4Gi", "cpu_requests": "2", "use_hw_template":
  | true, "parameters": {"CPU_FAMILY": 6, "CPU_MODEL": 94, "PHYSICAL_CPUS": 32, "PROCESSOR":
  | "Intel Core Processor (Skylake, IBRS)", "AMUN_INSPECTION_ID": "inspection-36446b52ac871852"}}'
  | template_method_name: get_inspection_job_template
  | template_method_parameters: '{"use_hw_template": true, "cpu_requests": "2", "memory_requests":
  | "4Gi"}'
  | kind: ConfigMap
  | metadata:
  | creationTimestamp: '2019-06-03T09:08:41Z'
  | labels:
  | app: thoth
  | component: amun-inspection
  | operator: workload
  | name: inspection-36446b52ac871852
  | namespace: thoth-test-core
  | resourceVersion: '100406497'
  | selfLink: /api/v1/namespaces/thoth-test-core/configmaps/inspection-36446b52ac871852
  | uid: 2e7ca2aa-85df-11e9-8ea5-fa163eda9ab7
  | : 422 Client Error: Unprocessable Entity for url: https://172.56.0.1:443/apis/template.openshift.io/v1/namespaces/thoth-test-core/processedtemplates
  | Traceback (most recent call last):
  | File "app.py", line 188, in cli
  | method_result = method(**method_parameters, template=template)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 629, in run_inspection_job
  | template = self.oc_process(self.amun_inspection_namespace, template)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 1391, in oc_process
  | response.raise_for_status()
  | File "/opt/app-root/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)

```

There are missing following parameters which should be propagated to the template:

* `THOTH_REGISTRY`
* `THOTH_INFRA_NAMESPACE`

**Comment by fridex** [comment]
This one is already fixed. Closing...
