### ISSUE TITLE
Regression on inspect endoint in stage

### ISSUE THREAD

**Issue by fridex** [thoth-station/amun-api#286]
As reported by @pacospace:

```
2020-01-06 11:03:43,462 [28] ERROR    amun.entrypoint:1891: Exception on /api/v1/inspect [POST]
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app-root/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 172, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/opt/app-root/src/amun/api_v1.py", line 132, in post_inspection
    _OPENSHIFT.create_inspection_imagestream(inspection_id)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 569, in create_inspection_imagestream
    "template=amun-inspection-imagestream", self.amun_infra_namespace
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 505, in _get_template
    self._raise_on_invalid_response_size(response)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 1964, in _raise_on_invalid_response_size
    f"Application misconfiguration - number of templates available in the infra namespace "
RuntimeError: Application misconfiguration - number of templates available in the infra namespace None is 0, should be 1.```

**Comment by goern** [comment]
@fridex Is this a deployment/ops problem?

**Comment by fridex** [comment]
yes, `amun-inspection-imagestream` template was not present in the namespace

**Comment by fridex** [comment]
I think we can close this one. Ack?
