### ISSUE TITLE
Error: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/amun-api#421]
**Describe the bug**
Submitting an example inspection job hits internal server error.

**To Reproduce**
1. Go to 'http://amun-api-thoth-test-core.cloud.paas.psi.redhat.com/api/v1/ui/'
2. Click on '/inspect'
3. Click on 'Try it out'
3. Click on 'Execute'
4. Scroll down to see the error message.

**Expected behavior**
A pod running for inspection job in `thoth-test-core` namespace.

**Comment by fridex** [comment]
```

2020-06-18 12:51:58,707  29 WARNING  thoth.common.openshift:299: Requested to assign parameter 'AMUN_RUN_MEMORY' (value '512Mi') to template but template does not provide the given parameter, forcing...
--
  | 2020-06-18 12:51:59,034  29 ERROR    amun.entrypoint:1892: Exception on /api/v1/inspect [POST]
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
  | response = self.full_dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
  | rv = self.handle_user_exception(e)
  | File "/opt/app-root/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
  | return cors_after_request(app.make_response(f(*args, **kwargs)))
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
  | reraise(exc_type, exc_value, tb)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
  | rv = self.dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
  | return self.view_functions[rule.endpoint](**req.view_args)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
  | response = function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
  | response = function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 184, in wrapper
  | response = function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
  | return function(**kwargs)
  | File "/opt/app-root/src/amun/api_v1.py", line 193, in post_inspection
  | parameters=parameters
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 776, in schedule_inspection
  | "workflow_parameters": workflow_parameters,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 1191, in _schedule_workflow
  | return workflow(**parameters)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 514, in submit_inspection_workflow
  | workflow_namespace=self.openshift.amun_inspection_namespace,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 481, in submit_workflow_from_template
  | workflow_namespace or namespace, workflow, parameters=workflow_parameters
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 447, in submit_workflow
  | namespace, body
  | File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/api/v1alpha1_api.py", line 57, in create_namespaced_workflow
  | (data) = self.create_namespaced_workflow_with_http_info(namespace, body, **kwargs)  # noqa: E501
  | File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/api/v1alpha1_api.py", line 138, in create_namespaced_workflow_with_http_info
  | collection_formats=collection_formats)
  | File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 330, in call_api
  | _preload_content, _request_timeout)
  | File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 161, in __call_api
  | _request_timeout=_request_timeout)
  | File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 373, in request
  | body=body)
  | File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/rest.py", line 275, in POST
  | body=body)
  | File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/rest.py", line 228, in request
  | raise ApiException(http_resp=r)
  | argo.workflows.client.rest.ApiException: (403)
  | Reason: Forbidden
  | HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 18 Jun 2020 12:51:58 GMT', 'Content-Length': '377'})
  | HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"workflows.argoproj.io is forbidden: User \"system:serviceaccount:thoth-test-core:amun-inspector-thoth-test-core\" cannot create workflows.argoproj.io in the namespace \"thoth-test-core\": no RBAC policy matched","reason":"Forbidden","details":{"group":"argoproj.io","kind":"workflows"},"code":403}


```

**Comment by goern** [comment]
looks like the root cause is a missing role binding, I will transfer this issue to thoth-application, as that is the place where we need to fix it.
