### ISSUE TITLE
split on None?

### ISSUE THREAD

**Issue by goern** [thoth-station/amun-api#50]
**Describe the bug**
```

[2018-10-30 11:33:26 +0000] [29] [ERROR] Exception in worker process
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
  | worker.init_process()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
  | self.load_wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
  | self.wsgi = self.app.wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
  | self.callable = self.load()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
  | return self.load_wsgiapp()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
  | return util.import_app(self.app_uri)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
  | __import__(module)
  | File "/opt/app-root/src/amun/entrypoint.py", line 35, in <module>
  | init_logging(logging_env_var_start='AMUN_LOG_')
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/logging.py", line 96, in init_logging
  | _SENTRY_DSN.rsplit('@', maxsplit=1)[1])
  | IndexError: list index out of range
  | [2018-10-30 11:33:26 +0000] [29] [INFO] Worker exiting (pid: 29)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by fridex** [comment]
What is sentry dsn value? There is a guard with recent releases.

**Comment by goern** [comment]
SENTRY_DSN was set to "teststring"

**Comment by fridex** [comment]
> SENTRY_DSN was set to "teststring"

Ack, that is not valid. I will add an error message for that.
