### ISSUE TITLE
Integration tests fail in test environment on TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by fridex** [thoth-station/amun-api#605]
**Describe the bug**

```
2021-02-24 10:04:57,184  31 ERROR    amun.entrypoint:1891: Exception on /api/v1/inspect [POST]
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app-root/lib64/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app-root/lib64/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/opt/app-root/src/amun/api_v1.py", line 220, in post_inspection
    send_messages=int(specification.get("send_messages")),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**To Reproduce**
1. Go to test environment
2. Trigger integration tests
3. See the error

**Comment by fridex** [comment]
This looks like some dev version of amun api is runinng. CC @KPostOffice I cannot see the reported line in the current master:

```
  File "/opt/app-root/src/amun/api_v1.py", line 220, in post_inspection
    send_messages=int(specification.get("send_messages")),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by KPostOffice** [comment]
This should have been fixed by https://github.com/AICoE/aicoe-cd/pull/246. Is this in the test env?

**Comment by fridex** [comment]
Does not look like relevant anymore. Maybe an old deployment.
